apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service-deployment
  labels:
    app: patient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
      - name: patient
        image: asia-south1-docker.pkg.dev/hackthon/hackthon-registery/patient-service:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  type: ClusterIP
  selector:
    app: patient
  ports:
  - port: 80
    targetport: 3000
    protocol: tcp
