name: DEV - Deploy to GCP Kubernetes

on:
  push:
    branches:
      - develop

env:
  GCP_PROJECT_ID: hackthon-391121
  GCP_REGION: asia-south
  GAR_REPOSITORY: dev-project

  IMAGE_NAME: asia-south1-docker.pkg.dev/hackthon/hackthon-registery/application-service
  IMAGE_TAG: latest
  GKE_CLUSTER: hackthon-gke-cluster
  GKE_REGION: as-south1

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Build
        uses: docker/setup-build-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.build-cache
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SA_KEY }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: gcloud auth configure-docker ${GCP_REGION}-docker.pkg.dev

      - name: Build, tag, and push image to Google Artifact Repository
        run: |
          docker build build --push \
            --tag ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest \
            -f ${{ github.workspace }}/application-service/Dockerfile .
          echo "IMAGE_URI=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_ENV

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_REGION }}

      - name: Deploy to GKE
        run: |
          kubectl apply -f ${{ github.workspace }}/application-service/deployment.yaml
          kubectl rollout restart deployment application-service-deployment

      - name: Wait for Deployment Rollout
        run: |
          kubectl rollout status deployment/worker --timeout=120s